export default {
  'Mini:OnOpen': Symbol('Mini:OnOpen'),
  'Mini:OnError': Symbol('Mini:OnError'),
  'Mini:OnMessage': Symbol('Mini:OnMessage'),
  'Mini:OnClose': Symbol('Mini:OnClose'),
  'Mini:OnSuccess': Symbol('Mini:OnSuccess'),
  'Mini:OnFail': Symbol('Mini:OnFail'),
  'Mini:OnComplete': Symbol('Mini:OnComplete'),
  'Mini:OnReadyState': Symbol('Mini:OnReadyState'),
  'Mini:SendSuccess': Symbol('Mini:SendSuccess'),
  'Mini:SendFail': Symbol('Mini:SendFail'),
  'Mini:SendComplete': Symbol('Mini:SendComplete'),
  'Mini:CloseSuccess': Symbol('Mini:CloseSuccess'),
  'Mini:CloseFail': Symbol('Mini:CloseFail'),
  'Mini:CloseComplete': Symbol('Mini:CloseComplete'),
  'Mini:Reconnect': Symbol('Mini:Reconnect'),
};
